### ISSUE TITLE
Fish Pond won't start

### ISSUE THREAD

**Issue by EmanueleS2** [Bappsack/UwU-Maker#1]
Hi, I tested out the bot and it's overall pretty good and it's not that much performance hungry (even tho I have an high tier PC).
I just wanted to point out that bot doesn't start Fish Pond minigames.
I made sure the game was set into proper resolution by checking settings and made sure the minigame window was in the "Start Game" state.

**Comment by Bappsack** [comment]
How do u know it works good if u can't even start the Minigame???

**Comment by EmanueleS2** [comment]
Because Woodcutter works for me, but it doesn't stop playing when it reaches enough points and also, it doesn't collect rewards.

**Comment by ridvang** [comment]
same, won't work on my end either. The others work pretty fine

**Comment by EmanueleS2** [comment]
Made my own tool from scratch, thank you though
